# запуск
clang-tidy-18 -p=cmake-build-debug src/common/library_test.cpp

# превратить все предупреждения clang-tidy в ошибки.
WarningsAsErrors: '*'

# Посмотреть полный список
clang-tidy-18 -list-checks

# Чтобы посмотреть вообще все доступные checks:
clang-tidy-18 -checks='*' -list-checks

# какие проверки реально применяются к нашему проекту из .clang-tidy.
clang-tidy-18 -checks='modernize-*,bugprone-*,performance-*,readability-*,-modernize-use-trailing-return-type' -list-checks

# взять одну конкретную проверку и посмотреть, как она находит проблему в коде.
# readability-magic-numbers
clang-tidy-18 -dump-config | grep -A 10 'readability-magic-numbers'
