# список доступных presets
cmake --list-presets
# указать preset для cmake
cmake --preset development
# указать preset для Build
cmake --build --preset development
# Это покажет реальную команду компилятора, которую запустил Ninja.
cmake --build --preset development --verbose
